#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)
# Check if there are any staged files
if [ -z "$STAGED_FILES" ]; then
    echo "No files are staged for commit."
else
    # Format files with black
    echo "$STAGED_FILES" | xargs -r poetry run black

    # Re-stage the files after formatting
    echo "$STAGED_FILES" | xargs -r git add
fi

# Exit with a zero status if everything is fine
exit 0
